api_key:
  key: "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"


model:
  name: "llama3-70b-8192" 
  temperature: 0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  max_tokens: 1024
  n: 1
  seed: 42